[conf]
default-lang = "fr"

[lang.en]
facture = "invoice"
devis="quotation"
coordonees_bancaires = "Bank details"
titulaire_du_compte = "Account holder"
banque = "Bank"
iban = "IBAN"
code_bic = "BIC code"
detail = "Detail"
details_des_operations = "Operation details"
pour_un_total = "For a total of"
et = "and"
heures = "hours"
quantite = "Quantity"
designation = "Description"
prix_unitaire_ht = "Unit price excl. tax"
prix_total_ht = "Total price excl. tax"
taux_journalier_moyen = "Average Daily Rate (ADR)"
reference = "Reference"
date = "Date"
n_client = "Client number"
intitule = "Title"
temps = "Time"
293b_vat = "VAT not applicable, article 293 B of the French General Tax Coder"

[lang.fr]
facture="facture"
devis="devis"
coordonees_bancaires="Coordonnées bancaires"
titulaire_du_compte="Titulaire du compte"
banque="Banque"
iban="IBAN"
code_bic="Code BIC"
detail="Détail"
details_des_operations="Détails des opérations"
pour_un_total="Pour un total de"
et="et"
heures="heures"
quantite="Qantité"
designation="Désignation"
prix_unitaire_ht="Prix unitaire HT"
prix_total_ht="Prix total HT"
taux_journalier_moyen="Taux Journalier Moyen (TJM)"
reference="Référence"
date="Date"
n_client="N° client"
intitule="Intitulé"
temps="Temps"
293b_vat = "TVA non applicable, art. 293 B du CGI"
